/**
 * 审查与合并 kernel 逻辑（spec §4.1，自 flowrun/merge.ts + ci.ts 迁入，逻辑不变）。
 * - mergeTaskPR：标准化合并 PR（--match-head-commit 防偷换）
 * - checkBranchProtection：默认分支保护探测
 * - createRevertPR：回滚 PR
 */

import { gh as ghCli } from "../util/gh.js"
import { escapeShellArg } from "../util/shell.js"

// ─── 可替换的 gh executor（用于测试） ───

export type GhFn = (args: string) => Promise<{ stdout: string; stderr: string }>

let mergeGhExecutor: GhFn | null = null

export function setMergeGhExecutor(fn: GhFn | null) {
  mergeGhExecutor = fn
}

async function gh(args: string): Promise<{ stdout: string; stderr: string }> {
  if (mergeGhExecutor) {
    return mergeGhExecutor(args)
  }
  return ghCli(args)
}

// ─── 类型 ───

export interface BranchProtectionStatus {
  exists: boolean
  requiredChecks: string[]
  requiresPR: boolean
  dismissesStale: boolean
}

// ─── Branch Protection ───

export async function checkBranchProtection(owner: string, repo: string): Promise<BranchProtectionStatus> {
  try {
    const { stdout } = await gh(`api repos/${owner}/${repo}/branches/main/protection`)
    const data = JSON.parse(stdout)

    const checks: string[] = []
    const requiredPulls = data?.required_pull_request_reviews ?? null
    const requiredChecks = data?.required_status_checks?.checks ?? []

    for (const c of requiredChecks) {
      checks.push(c.context)
    }

    return {
      exists: true,
      requiredChecks: checks,
      requiresPR: !!requiredPulls,
      dismissesStale: requiredPulls?.dismiss_stale_reviews ?? false,
    }
  } catch {
    return {
      exists: false,
      requiredChecks: [],
      requiresPR: false,
      dismissesStale: false,
    }
  }
}

// ─── PR 合并操作 ───

/**
 * Task PR 合并（带 --match-head-commit 安全检查）。
 *
 * 步骤：
 * 1. 验证 verifiedSha 非空
 * 2. 使用 gh pr merge --squash --delete-branch --match-head-commit <verifiedSha>
 * 3. 失败时返回错误
 */
export async function mergeTaskPR(prNumber: number, verifiedSha: string): Promise<{ success: boolean; error?: string }> {
  if (!verifiedSha) {
    return { success: false, error: "verifiedSha is required for merge --match-head-commit" }
  }

  try {
    // --match-head-commit 确保只有 verified 的 commit 才会被合并
    await gh(`pr merge ${prNumber} --squash --delete-branch --match-head-commit '${verifiedSha}'`)
    return { success: true }
  } catch (err) {
    return { success: false, error: String(err) }
  }
}

// ─── Revert ───

export async function createRevertPR(prNumber: number, reason: string): Promise<{ prNumber?: number; error?: string }> {
  try {
    const { stdout } = await gh(`pr view ${prNumber} --json headRefName,headRepository,body,title`)
    const pr = JSON.parse(stdout)

    const revertTitle = `revert: ${pr.title}`
    const revertBody = `Reverts #${prNumber}\n\nReason: ${reason}\n\nAuto-generated by opencode-cabbage.`

    const { stdout: newPR } = await gh(
      `pr create --title '${escapeShellArg(revertTitle)}' --body '${escapeShellArg(revertBody)}' --base main --head main`,
    )
    return { prNumber: parseInt(newPR.trim().split("/").pop() || "0", 10) }
  } catch (err) {
    return { error: String(err) }
  }
}
