import type {
  FlowRun, PRCheckpoints, Checkpoint, TaskState,
} from "./types.js"
import { canMerge } from "./gate.js"
import { gh } from "../util/gh.js"

export interface BranchProtectionStatus {
  exists: boolean
  requiredChecks: string[]
  requiresPR: boolean
  dismissesStale: boolean
}

export interface MergeGateResult {
  allowed: boolean
  reason?: string
  checkpointResults: Record<string, "pending" | "pass" | "fail" | "skipped">
}

export async function checkBranchProtection(owner: string, repo: string): Promise<BranchProtectionStatus> {
  try {
    const { stdout } = await gh(`api repos/${owner}/${repo}/branches/main/protection`)
    const data = JSON.parse(stdout)

    const checks: string[] = []
    const requiredPulls = data?.required_pull_request_reviews ?? null
    const requiredChecks = data?.required_status_checks?.checks ?? []

    for (const c of requiredChecks) {
      checks.push(c.context)
    }

    return {
      exists: true,
      requiredChecks: checks,
      requiresPR: !!requiredPulls,
      dismissesStale: requiredPulls?.dismiss_stale_reviews ?? false,
    }
  } catch {
    return {
      exists: false,
      requiredChecks: [],
      requiresPR: false,
      dismissesStale: false,
    }
  }
}

export function validateCheckpoint(cp: Checkpoint): "pending" | "pass" | "fail" {
  if (cp.status === "pass") return "pass"
  if (cp.status === "fail") return "fail"
  return "pending"
}

export function validatePRCheckpoints(checkpoints: PRCheckpoints): MergeGateResult {
  const gates: Record<string, Checkpoint> = {
    localChecks: checkpoints.localChecks,
    ciChecks: checkpoints.ciChecks,
    reviewerApproval: checkpoints.reviewerApproval,
    goalVerification: checkpoints.goalVerification,
    branchProtection: checkpoints.branchProtection,
  }

  const results: Record<string, "pending" | "pass" | "fail" | "skipped"> = {}

  for (const [name, cp] of Object.entries(gates)) {
    results[name] = validateCheckpoint(cp)
  }

  const failures = Object.entries(gates).filter(([_, cp]) => cp.status === "fail")
  if (failures.length > 0) {
    return {
      allowed: false,
      reason: `Failed checkpoints: ${failures.map(([k]) => k).join(", ")}`,
      checkpointResults: results,
    }
  }

  const pending = Object.entries(gates).filter(([_, cp]) => cp.status === "pending")
  if (pending.length > 0) {
    return {
      allowed: false,
      reason: `Pending checkpoints: ${pending.map(([k]) => k).join(", ")}`,
      checkpointResults: results,
    }
  }

  return { allowed: true, checkpointResults: results }
}

export function canAutoMergeTask(flowRun: FlowRun, task: TaskState, protection: BranchProtectionStatus): MergeGateResult {
  const flowGate = canMerge(flowRun)
  if (!flowGate.allowed) {
    return { allowed: false, reason: flowGate.reason, checkpointResults: {} }
  }

  if (task.status === "merged") {
    return { allowed: false, reason: "Task already merged", checkpointResults: {} }
  }

  if (task.status !== "reviewing") {
    return { allowed: false, reason: `Task status is ${task.status}, expected reviewing`, checkpointResults: {} }
  }

  if (!task.prCheckpoints) {
    return { allowed: false, reason: "No PR checkpoints recorded", checkpointResults: {} }
  }

  const prResult = validatePRCheckpoints(task.prCheckpoints)
  if (!prResult.allowed) return prResult

  if (!protection.exists) {
    prResult.checkpointResults.branchProtection = "fail"
    return {
      allowed: false,
      reason: "Branch protection not enabled on main",
      checkpointResults: prResult.checkpointResults,
    }
  }

  prResult.checkpointResults.branchProtection = "pass"
  return prResult
}

export async function mergePR(prNumber: number): Promise<{ success: boolean; error?: string }> {
  try {
    await gh(`pr merge ${prNumber} --squash --delete-branch`)
    return { success: true }
  } catch (err) {
    return { success: false, error: String(err) }
  }
}

export async function createRevertPR(prNumber: number, reason: string): Promise<{ prNumber?: number; error?: string }> {
  try {
    const { stdout } = await gh(`pr view ${prNumber} --json headRefName,headRepository,body,title`)
    const pr = JSON.parse(stdout)

    const revertTitle = `revert: ${pr.title}`
    const revertBody = `Reverts #${prNumber}\n\nReason: ${reason}\n\nAuto-generated by opencode-cabbage.`

    const { stdout: newPR } = await gh(`pr create --title '${revertTitle}' --body '${revertBody}' --base main --head main`)
    return { prNumber: parseInt(newPR.trim().split("/").pop() || "0", 10) }
  } catch (err) {
    return { error: String(err) }
  }
}
